/**
 * Pure helpers that turn a synthesized CloudFormation template into Bruno
 * request files. No AWS or filesystem access here so it can be unit tested.
 */

export const GENERATED_MARKER = 'Generated by scripts/sync-collection.ts';

export interface Route {
  method: string;
  path: string;
  sampleBody?: Record<string, unknown>;
}

type Template = { Resources: Record<string, { Type: string; Properties?: any }> };

export function extractRoutes(template: Template): Route[] {
  const resources = template.Resources;

  const resolvePath = (ref: any): string => {
    if (ref?.['Fn::GetAtt']?.[1] === 'RootResourceId') return '';
    const resource = resources[ref?.Ref];
    if (resource?.Type !== 'AWS::ApiGateway::Resource') {
      throw new Error(`Cannot resolve API resource ${JSON.stringify(ref)}`);
    }
    return `${resolvePath(resource.Properties.ParentId)}/${resource.Properties.PathPart}`;
  };

  const routes: Route[] = [];
  for (const res of Object.values(resources)) {
    if (res.Type !== 'AWS::ApiGateway::Method') continue;
    const { HttpMethod, ResourceId, RequestModels } = res.Properties;
    if (HttpMethod === 'OPTIONS') continue;

    const modelRef = RequestModels?.['application/json']?.Ref;
    const schema = modelRef ? resources[modelRef]?.Properties?.Schema : undefined;
    routes.push({
      method: HttpMethod,
      path: resolvePath(ResourceId) || '/',
      ...(schema && { sampleBody: sampleFromSchema(schema) }),
    });
  }
  return routes.sort((a, b) => a.path.localeCompare(b.path) || a.method.localeCompare(b.method));
}

function sampleFromSchema(schema: any): Record<string, unknown> {
  const sample: Record<string, unknown> = {};
  for (const [name, prop] of Object.entries<any>(schema.properties ?? {})) {
    sample[name] =
      prop.type === 'number' || prop.type === 'integer' ? 1
      : prop.type === 'boolean' ? true
      : `hello from bruno (${name})`;
  }
  return sample;
}

/** Folder and file name (relative to the collection root) for a route. */
export function requestFile(route: Route): { folder: string; file: string } {
  const segments = route.path.split('/').filter(Boolean);
  return {
    folder: segments[0] ?? 'root',
    file: `${route.method.toLowerCase()}-${segments.join('-') || 'root'}.bru`,
  };
}

export function renderRequest(route: Route, seq: number): string {
  const method = route.method.toLowerCase();
  const indent = (text: string) => text.split('\n').map((l) => `  ${l}`).join('\n');
  const body = route.sampleBody
    ? `\nbody:json {\n${indent(JSON.stringify(route.sampleBody, null, 2))}\n}\n`
    : '';

  return `meta {
  name: ${route.method} ${route.path}
  type: http
  seq: ${seq}
}

${method} {
  url: {{baseUrl}}${route.path}
  body: ${route.sampleBody ? 'json' : 'none'}
  auth: inherit
}
${body}
assert {
  res.status: lt 300
  res.body.message: isString
}

docs {
  ${GENERATED_MARKER} from the CDK template - edits are overwritten.
}
`;
}

export function renderEnvironment(vars: Record<string, string>): string {
  const lines = Object.entries(vars).map(([k, v]) => `  ${k}: ${v}`);
  return `vars {\n${lines.join('\n')}\n}\n`;
}

/** Reads `key: value` pairs from an existing Bruno environment file. */
export function parseEnvironment(content: string): Record<string, string> {
  const vars: Record<string, string> = {};
  for (const match of content.matchAll(/^\s+([\w-]+):\s*(.*)$/gm)) vars[match[1]] = match[2].trim();
  return vars;
}
